// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const creatUser = `-- name: CreatUser :one
INSERT INTO users (id, created_at, updated_at, email)
VALUES (
       get_random_uuid(),
       now(),
       now(),
       $1
)
RETURNING id, created_at, updated_at, email
`

func (q *Queries) CreatUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, creatUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}
